### ISSUE TITLE
Python "borks" after 1 minute

### ISSUE THREAD

**Issue by willem640** [drmly/drmly#1]
```
Traceback (most recent call last):
  File "folder.py", line 255, in <module>
    deep_dream(model_path, args.output)
  File "folder.py", line 157, in deep_dream
    loss = tf.reduce_mean(t_obj)
  File "/home/willem/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1411, in reduce_mean
    name=name)
  File "/home/willem/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2568, in _mean
    keep_dims=keep_dims, name=name)
  File "/home/willem/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 350, in _apply_op_helper
    g = ops._get_graph_from_inputs(_Flatten(keywords.values()))
  File "/home/willem/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4636, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "/home/willem/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4572, in _assert_same_graph
    original_item))
ValueError: Tensor("Const:0", shape=(3,), dtype=int32) must be from the same graph as Tensor("strided_slice_2:0", shape=(?, ?, ?), dtype=float32).
```
This happened with a ~10 second webm

**Comment by willem640** [comment]
after this happens, it seems to continue removing or adding sound (ffmpeg) before telling me it "borked"

**Comment by TableMountain** [comment]
oh hey! wow i'm sorry i didn't see this. yeah that was a bug I made. I put a patch up, which is the latest commit. I really think that should fix it no problem. let me know if not

**Comment by TableMountain** [comment]
yeah so basically I was implementing channels but it doesn't work with multiple images for some reason so i've just pushed off figuring out what's wrong for now and only doing videos without channels. lmk if u want to work on figuring out how to get channels to work on multiple images. thoughts?

**Comment by TableMountain** [comment]
also you should be able to just put an image file on the desktop and that will automatically output an image for you in the bind/images directory, just as a test that you can see it works
