### ISSUE TITLE
cannot launch drmly

### ISSUE THREAD

**Issue by maxugly** [drmly/drmly#4]
I have followed all of the instructions on the readme and everything appeared to work until the last step

I tried these two things and not sure what else I can try to do, I am not Linux savvy..

[max@max ~]$ drmly
bash: drmly: command not found

[max@max ~]$ /home/max/go/bin/drmly
(drmly:1816): Gtk-WARNING **: 06:48:43.741: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(drmly:1816): Gtk-WARNING **: 06:48:43.741: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(drmly:1816): Gtk-WARNING **: 06:48:43.741: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(drmly:1816): Gtk-WARNING **: 06:48:43.741: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(drmly:1816): Gtk-WARNING **: 06:48:43.741: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(drmly:1816): Gtk-WARNING **: 06:48:43.741: Theme parsing error: gtk.css:83:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version
INFO[0000] click this: http://localhost:8080            
INFO[0000] dir of bind is /home/max/go/bin              
INFO[0000] Hello max <3100LTC                           
INFO[0000] ====                                         
INFO[0000] Id: 1000                                     
INFO[0000] Username: max                                
INFO[0000] Home Dir: /home/max                          
INFO[0000] this is the normal user: max                 
INFO[0000] bind folder  basePath: /home/max/Desktop/bind 
dir is  /home/max/go/bin
INFO[0000] skipping copying templates dirstat /home/max/go/bin/public: no such file or directory 
INFO[0000] bind dirs ensured!                           
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

panic: html/template: pattern matches no files: `/home/max/Desktop/bind/public/tmpl/*.html`

goroutine 1 [running]:
html/template.Must(...)
        /usr/lib/go/src/html/template/template.go:372
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc000116dc0, 0xc00002c210, 0x29)
        /home/max/go/src/github.com/gin-gonic/gin/gin.go:185 +0x362
main.InitializeServer(0xc6d40e, 0xc, 0x4e35e6)
        /home/max/go/src/github.com/drmly/drmly/server.go:35 +0x257
main.web()
        /home/max/go/src/github.com/drmly/drmly/server.go:19 +0x3a
main.(*Service).Manage(0xc00032ff18, 0xb, 0xc82e84, 0x2c, 0x138d570)
        /home/max/go/src/github.com/drmly/drmly/daemon.go:62 +0x107
main.main()
        /home/max/go/src/github.com/drmly/drmly/main.go:17 +0x178

**Comment by TableMountain** [comment]
yes the gtk indicates to me it has to do with you're using linux and i'm using mac. Unfortunataley I never cross tested this fully. Sorry for the delayed reply!
